"""Generic Adapter - Handles standard CSV/Excel formats and unknown platforms"""

from .base_adapter import BaseAdapter


class GenericAdapter(BaseAdapter):
    """Generic adapter for standard formats and unknown platforms"""
    
    PLATFORM_NAME = "generic"
    
    COLUMN_MAPPINGS = {
        'order_id': 'invoice_number',
        'order_number': 'invoice_number',
        'invoice_no': 'invoice_number',
        'invoice_id': 'invoice_number',
        'order_no': 'invoice_number',
        'invoice_number': 'invoice_number',
        'bill_number': 'invoice_number',
        'bill_no': 'invoice_number',
        'transaction_id': 'invoice_number',
        'txn_id': 'invoice_number',
        'order_date': 'invoice_date',
        'date': 'invoice_date',
        'transaction_date': 'invoice_date',
        'sale_date': 'invoice_date',
        'bill_date': 'invoice_date',
        'invoice_date': 'invoice_date',
        'dated': 'invoice_date',
        'customer_gst': 'customer_gstin',
        'buyer_gstin': 'customer_gstin',
        'gstin': 'customer_gstin',
        'customer_gstin_no': 'customer_gstin',
        'buyer_gst': 'customer_gstin',
        'recipient_gstin': 'customer_gstin',
        'ship_state': 'place_of_supply',
        'shipping_state': 'place_of_supply',
        'supply_state': 'place_of_supply',
        'state': 'place_of_supply',
        'customer_state': 'place_of_supply',
        'buyer_state': 'place_of_supply',
        'place_of_supply': 'place_of_supply',
        'pos': 'place_of_supply',
        'recipient_state': 'place_of_supply',
        'hsn': 'hsn_code',
        'hsn_code_no': 'hsn_code',
        'hsn_no': 'hsn_code',
        'hsn_code': 'hsn_code',
        'hsn_number': 'hsn_code',
        'product_code': 'hsn_code',
        'gst_rate': 'tax_rate',
        'gst_percentage': 'tax_rate',
        'tax_percentage': 'tax_rate',
        'rate': 'tax_rate',
        'tax_rate': 'tax_rate',
        'gst_%': 'tax_rate',
        'tax_%': 'tax_rate',
        'order_value': 'taxable_value',
        'amount': 'taxable_value',
        'value': 'taxable_value',
        'net_amount': 'taxable_value',
        'total_amount': 'taxable_value',
        'taxable_value': 'taxable_value',
        'taxable_amount': 'taxable_value',
        'base_amount': 'taxable_value',
        'qty': 'quantity',
        'item_qty': 'quantity',
        'quantity': 'quantity',
        'units': 'quantity',
        'qty_': 'quantity',
        'seller_state': 'supplier_state',
        'from_state': 'supplier_state',
        'origin_state': 'supplier_state',
        'supplier_state': 'supplier_state',
        'order_item_id': 'order_item_id',
        'sku': 'sku',
        'product_sku': 'sku',
        'item_code': 'sku',
        'product_name': 'product_name',
        'item_name': 'product_name',
        'description': 'product_name',
        'product_description': 'product_name',
        'customer_name': 'customer_name',
        'buyer_name': 'customer_name',
        'recipient_name': 'customer_name',
        'cgst_amount': 'cgst',
        'sgst_amount': 'sgst',
        'igst_amount': 'igst',
        'cgst': 'cgst',
        'sgst': 'sgst',
        'igst': 'igst',
        'central_tax': 'cgst',
        'state_tax': 'sgst',
        'integrated_tax': 'igst',
        'grand_total': 'total_amount',
        'invoice_total': 'total_amount',
        'bill_total': 'total_amount',
        'total': 'total_amount',
    }
    
    def get_column_mappings(self) -> dict:
        return self.COLUMN_MAPPINGS
